import './shims-b90d3d7b.js';
import 'fs';
import 'path';
export { h as handler } from './handler-8d3e98db.js';
import 'url';
import './server/app.js';
import './manifest.js';
import 'node:http';
import 'node:https';
import 'node:zlib';
import 'node:stream';
import 'node:util';
import 'node:url';
import 'net';
import 'querystring';
import 'stream';
